[site]
title = "Yuxiang Lin"
description = "Personal academic homepage of Yuxiang Lin."
favicon = "/favicon.svg"
last_updated = "September 9, 2026"

[author]
name = "Yuxiang Lin"
title = "Computational Biology Researcher"
institution = "Xiamen University"
avatar = "/bio.jpg"

[social]
# Contact information (leave blank or delete to hide)

email = "linyuxiang@stu.xmu.edu.cn"
location = ""
location_url = ""
location_details = []
google_scholar = "https://scholar.google.com/citations?user=TgJ6W0YAAAAJ&hl=en"
orcid = "https://orcid.org/0000-0001-8854-2995"
github = "https://github.com/lenislin"
linkedin = ""

[features]
# Show a like button on the about page
enable_likes = false

# Display all subpages on a single page
enable_one_page_mode = false

[i18n]
enabled = true
locales = ["zh", "en"]
default_locale = "en"
# "auto" means the locale will be determined by the browser's language setting, "fixed" means the locale will be fixed to the default locale (but can be switched still, if you want to disable, set "enable=false")
mode = "auto"
fixed_locale = "en"
# If true, PRISM will remember user's language preference in browser's localStorage
persist = true
# Show a language switcher on the top right corner
switcher = true

[i18n.labels]
zh = "中文"
en = "English"

[[navigation]]
title = "About"
type = "page"
target = "about"
href = "/"

[[navigation]]
title = "Publications"
type = "page"
target = "publications"
href = "/publications"

[[navigation]]
title = "CV"
type = "page"
target = "cv"
href = "/cv"
